(define (average x y) (/ (+ x y) 2))
(define (fixed-point f start)
  (define tolerance 0.00001)
  (define (close-enuf? u v)
    (< (abs (- u v)) tolerance))
  (define (iter old new)
    (if (close-enuf? old new)
      new
      (iter new (f new))))
  (iter start (f start)))
(define (sqrt x)
  (fixed-point
    (lambda(y) (average (/ x y) y))
    1))
(define dx 0.000001)
(define deriv
  (lambda(f) 
    (lambda(x)
      (/ (- (f (+ x dx))
            (f x))
         dx))))
(define (newton f guess)
  (define df (deriv f))
  (fixed-point (lambda(x) (- x (/ (f x) (df x))))
               guess))
(define (newton-sqrt x)
  (newton (lambda(y) (- x (square y)))
          1))
