#lang sicp
(define (plus m n)
      (lambda (f)
        (lambda (x)
          ((m f) ((n f) x)))))
(define (add-1 n)
  (lambda (f)
    (lambda (x)
      (f ((n f) x)))))
(define (mul m n)
  (lambda (f)
    (lambda (x)
      ((m (n f)) x))))
(define zero (lambda (f) (lambda (x) x)))
(define one (lambda (f) (lambda (x) (f x))))
(define two (lambda (f) (lambda (x) (f (f x)))))

(define (print num) ((num (lambda (n) (+ 1 n))) 0))