sudo update-alternatives --install /usr/bin/clang 						clang 				/usr/bin/clang-4.0 40
sudo update-alternatives --install /usr/bin/clang-format-diff 			clang-format-diff 	/usr/bin/clang-format-diff-4.0 40
sudo update-alternatives --install /usr/bin/clang++ 					clang++ 			/usr/bin/clang++-4.0 40
sudo update-alternatives --install /usr/bin/clang-import-test 			clang-import-test 	/usr/bin/clang-import-test-4.0 40
sudo update-alternatives --install /usr/bin/clang-apply-replacements 	clang-apply-replacements /usr/bin/clang-apply-replacements-4.0 40
sudo update-alternatives --install /usr/bin/clang-include-fixer	 		clang-include-fixer /usr/bin/clang-include-fixer-4.0 40
sudo update-alternatives --install /usr/bin/clang-change-namespace 		clang-change-namespace /usr/bin/clang-change-namespace-4.0 40
sudo update-alternatives --install /usr/bin/clang-offload-bundler 		clang-offload-bundler /usr/bin/clang-offload-bundler-4.0 40
sudo update-alternatives --install /usr/bin/clang-check 				clang-check 		/usr/bin/clang-check-4.0 40
sudo update-alternatives --install /usr/bin/clang-query 				clang-query 		/usr/bin/clang-query-4.0 40
sudo update-alternatives --install /usr/bin/clang-cl 					clang-cl 			/usr/bin/clang-cl-4.0 40
sudo update-alternatives --install /usr/bin/clang-rename 				clang-rename 		/usr/bin/clang-rename-4.0 40
sudo update-alternatives --install /usr/bin/clang-cpp 					clang-cpp 			/usr/bin/clang-cpp-4.0 40
sudo update-alternatives --install /usr/bin/clang-reorder-fields		clang-reorder-fields /usr/bin/clang-reorder-fields-4.0 40
sudo update-alternatives --install /usr/bin/clang-format 				clang-format 		/usr/bin/clang-format-4.0 40
sudo update-alternatives --install /usr/bin/clang-tblgen 				clang-tblgen 		/usr/bin/clang-tblgen-4.0 40