/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_TEST_H_RPCGEN
#define _RPC_TEST_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define TEST ((rpc_uint)32478345945)
#define VER ((rpc_uint)1)

#ifdef __cplusplus
#define TEST ((rpc_uint)1)
extern "C" char ** test_1(char **, CLIENT *);
extern "C" char ** test_1_svc(char **, struct svc_req *);

#elif __STDC__
#define TEST ((rpc_uint)1)
extern  char ** test_1(char **, CLIENT *);
extern  char ** test_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define TEST ((rpc_uint)1)
extern  char ** test_1();
extern  char ** test_1_svc();
#endif /* Old Style C */

#endif /* !_RPC_TEST_H_RPCGEN */
