(define (sqrt x)
  (define (average x y) (/ (+ x y) 2))
  (define tolerance 0.0001)
  (define (good-enuf? y)
    (< (abs (- (+ y y) x)) tolerance))
  (define (improve y)
    (average (/ x y) y))
  (define (try y)
    (if (good-enuf? y)
      y
      (try (improve y))))
    (try 1))
